#define VIRSH_OUTPUT_MAX 8192

enum {
    VIRSH_DOMSTATE_REASON_SHUTOFF_CRASHED,
    VIRSH_DOMSTATE_REASON_SHUTOFF_FAILED,
    VIRSH_DOMSTATE_REASON_SHUTOFF_DAEMON,
    VIRSH_DOMSTATE_REASON_CRASHED_UNKNOWN,
    VIRSH_DOMSTATE_REASON_CRASHED_PANICKED,
    VIRSH_DOMSTATE_REASON_MAX,
};

const char* abnormal_state_reason_arr[VIRSH_DOMSTATE_REASON_MAX]= {
    [VIRSH_DOMSTATE_REASON_SHUTOFF_CRASHED] = "shut off (crashed)",
    [VIRSH_DOMSTATE_REASON_SHUTOFF_FAILED] = "shut off (failed)",
    [VIRSH_DOMSTATE_REASON_SHUTOFF_DAEMON] = "shut off (daemon)",
    [VIRSH_DOMSTATE_REASON_CRASHED_UNKNOWN] = "crashed (unknown)",
    [VIRSH_DOMSTATE_REASON_CRASHED_PANICKED] = "crashed (panicked)",
};

enum {
    VIRSH_DOMSTATE_REASON_RUNNING_UNKNOWN,
    VIRSH_DOMSTATE_REASON_RUNNING_BOOTED,
    VIRSH_DOMSTATE_REASON_RUNNING_MIGRATED,
    VIRSH_DOMSTATE_REASON_RUNNING_RESTORED,
    VIRSH_DOMSTATE_REASON_RUNNING_CRASHED,
    VIRSH_DOMSTATE_REASON_NORMAL_MAX,
};

const char* normal_state_reason_arr[VIRSH_DOMSTATE_REASON_NORMAL_MAX]= {
    [VIRSH_DOMSTATE_REASON_RUNNING_UNKNOWN] = "running (unknown)",
    [VIRSH_DOMSTATE_REASON_RUNNING_BOOTED] = "running (booted)",
    [VIRSH_DOMSTATE_REASON_RUNNING_MIGRATED] = "running (migrated)",
    [VIRSH_DOMSTATE_REASON_RUNNING_RESTORED] = "running (restored)",
    [VIRSH_DOMSTATE_REASON_RUNNING_CRASHED] = "running (crashed)",
};

bool is_abnormal_state_reason(const char*);